import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ReactQueryWrapper from "@/react-query/ReactQueryWrapper";
import RecoilRootWrapper from "@/recoil/RecoilRootWrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/notosanskr.css" />
      </head>
      <body className={inter.className}>
        <div id="root" style={{ height: "auto !important" }}>
          <ReactQueryWrapper>
            <RecoilRootWrapper>
              <div className="flex min-h-screen flex-col" style={{ height: "auto !important", minHeight: "0px !important" }}>
                {/* Header */}
                <Header />
                {children}
                {/* Footer */}
                <Footer />
              </div>
            </RecoilRootWrapper>
          </ReactQueryWrapper>
        </div>
      </body>
    </html>
  );
}
