import { ItemData } from "@/interface/ItemEquipment";
import { atom } from "recoil";

export const ocidState = atom<string>({
  key: "ocidState",
  default: "",
});

export const itemDataState = atom<ItemData>({
  key: "itemDataState",
  default: {
    item_equipment_part: "",
    item_equipment_slot: "",
    item_name: "",
    item_icon: "",
    item_description: null,
    item_shape_name: "",
    item_shape_icon: "",
    item_gender: null,
    item_total_option: {
      str: "",
      dex: "",
      int: "",
      luk: "",
      max_hp: "",
      max_mp: "",
      attack_power: "",
      magic_power: "",
      armor: "",
      speed: "",
      jump: "",
      boss_damage: "",
      ignore_monster_armor: "",
      all_stat: "",
      damage: "",
      equipment_level_decrease: 0,
      max_hp_rate: "",
      max_mp_rate: "",
    },
    item_base_option: {
      str: "",
      dex: "",
      int: "",
      luk: "",
      max_hp: "",
      max_mp: "",
      attack_power: "",
      magic_power: "",
      armor: "",
      speed: "",
      jump: "",
      boss_damage: "",
      ignore_monster_armor: "",
      all_stat: "",
      max_hp_rate: "",
      max_mp_rate: "",
      base_equipment_level: 0,
    },
    potential_option_grade: null,
    additional_potential_option_grade: null,
    potential_option_1: null,
    potential_option_2: null,
    potential_option_3: null,
    additional_potential_option_1: null,
    additional_potential_option_2: null,
    additional_potential_option_3: null,
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "",
      dex: "",
      int: "",
      luk: "",
      max_hp: "",
      max_mp: "",
      attack_power: "",
      magic_power: "",
    },
    item_add_option: {
      str: "",
      dex: "",
      int: "",
      luk: "",
      max_hp: "",
      max_mp: "",
      attack_power: "",
      magic_power: "",
      armor: "",
      speed: "",
      jump: "",
      boss_damage: "",
      damage: "",
      all_stat: "",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "",
    cuttable_count: "",
    golden_hammer_flag: "",
    scroll_resilience_count: "",
    scroll_upgradeable_count: "",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "",
      dex: "",
      int: "",
      luk: "",
      max_hp: "",
      max_mp: "",
      attack_power: "",
      magic_power: "",
      armor: "",
      speed: "",
      jump: "",
    },
    starforce: "",
    starforce_scroll_flag: "",
    item_starforce_option: {
      str: "",
      dex: "",
      int: "",
      luk: "",
      max_hp: "",
      max_mp: "",
      attack_power: "",
      magic_power: "",
      armor: "",
      speed: "",
      jump: "",
    },
    special_ring_level: 0,
    date_expire: null,
  },
});

export const itemDetailPopupState = atom<boolean>({
  key: "itemDetailPopupState",
  default: false,
});
